openapi: 3.0.1
info:
  title: Excel Tools API
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /partir-excel:
    post:
      operationId: partirExcel
      summary: Divide un archivo Excel en m√∫ltiples CSV
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                  example: ventas.xlsx
      responses:
        "200":
          description: Archivo procesado correctamente
          content:
            application/json:
              schema:
                type: object